# coding: utf-8

"""
    Metric Handling Backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class PerformanceForFileLines(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'global_average': 'str'
    }

    attribute_map = {
        'global_average': 'global_average'
    }

    def __init__(self, global_average=None):  # noqa: E501
        """PerformanceForFileLines - a model defined in OpenAPI"""  # noqa: E501

        self._global_average = None
        self.discriminator = None

        if global_average is not None:
            self.global_average = global_average

    @property
    def global_average(self):
        """Gets the global_average of this PerformanceForFileLines.  # noqa: E501


        :return: The global_average of this PerformanceForFileLines.  # noqa: E501
        :rtype: str
        """
        return self._global_average

    @global_average.setter
    def global_average(self, global_average):
        """Sets the global_average of this PerformanceForFileLines.


        :param global_average: The global_average of this PerformanceForFileLines.  # noqa: E501
        :type: str
        """

        self._global_average = global_average

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PerformanceForFileLines):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
