# coding: utf-8

"""
    Metric Handling Backend

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    OpenAPI spec version: 0.0.1
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class PyflameProfile(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'start_timestamp': 'int',
        'end_timestamp': 'int',
        'pyflame_output': 'str'
    }

    attribute_map = {
        'start_timestamp': 'start_timestamp',
        'end_timestamp': 'end_timestamp',
        'pyflame_output': 'pyflame_output'
    }

    def __init__(self, start_timestamp=None, end_timestamp=None, pyflame_output=None):  # noqa: E501
        """PyflameProfile - a model defined in OpenAPI"""  # noqa: E501

        self._start_timestamp = None
        self._end_timestamp = None
        self._pyflame_output = None
        self.discriminator = None

        if start_timestamp is not None:
            self.start_timestamp = start_timestamp
        if end_timestamp is not None:
            self.end_timestamp = end_timestamp
        if pyflame_output is not None:
            self.pyflame_output = pyflame_output

    @property
    def start_timestamp(self):
        """Gets the start_timestamp of this PyflameProfile.  # noqa: E501


        :return: The start_timestamp of this PyflameProfile.  # noqa: E501
        :rtype: int
        """
        return self._start_timestamp

    @start_timestamp.setter
    def start_timestamp(self, start_timestamp):
        """Sets the start_timestamp of this PyflameProfile.


        :param start_timestamp: The start_timestamp of this PyflameProfile.  # noqa: E501
        :type: int
        """

        self._start_timestamp = start_timestamp

    @property
    def end_timestamp(self):
        """Gets the end_timestamp of this PyflameProfile.  # noqa: E501


        :return: The end_timestamp of this PyflameProfile.  # noqa: E501
        :rtype: int
        """
        return self._end_timestamp

    @end_timestamp.setter
    def end_timestamp(self, end_timestamp):
        """Sets the end_timestamp of this PyflameProfile.


        :param end_timestamp: The end_timestamp of this PyflameProfile.  # noqa: E501
        :type: int
        """

        self._end_timestamp = end_timestamp

    @property
    def pyflame_output(self):
        """Gets the pyflame_output of this PyflameProfile.  # noqa: E501


        :return: The pyflame_output of this PyflameProfile.  # noqa: E501
        :rtype: str
        """
        return self._pyflame_output

    @pyflame_output.setter
    def pyflame_output(self, pyflame_output):
        """Sets the pyflame_output of this PyflameProfile.


        :param pyflame_output: The pyflame_output of this PyflameProfile.  # noqa: E501
        :type: str
        """

        self._pyflame_output = pyflame_output

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, PyflameProfile):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
