build:
  stage: build
  script:
    - docker build --tag=playground_application .

deploy:
  stage: deploy
  script:
    - docker run --cap-add=SYS_PTRACE -p 4000:8081 playground_application
  only:
    - master
