openapi: 3.0.0
info:
  version: 0.0.1
  title: Metric Handling Backend
servers:
  - url: http://localhost:8080/api
paths:
  /metrics/requests/profile/pyflame:
    post:
      summary: Add a new profile using the pyflame format
      operationId: add_pyflame_profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PyflameProfile'
      responses:
        '400':
          description: Error processing
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddedEntityResponse'
  /metrics/application/version:
    get:
      summary: Get all versions of an application
      operationId: get_application_versions
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllApplicationVersions'
  /metrics/performance/for_file:
    get:
      summary: Get performance information for particular file
      operationId: get_performance_for_file
      parameters:
        - name: filename
          in: query
          required: true
          schema:
            type: string
        - name: version
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PerformanceForFile'
        '400':
          description: Invalid filename
components:
  schemas:
    PerformanceForFile:
      type: object
      properties:
        global_average_for_file:
          type: number
          format: double
        lines:
          type: object
          additionalProperties:
            type: object
            properties:
              global_average:
                type: number
                format: double
    PyflameProfile:
      type: object
      properties:
        start_timestamp:
          type: string
          format: date-time
        end_timestamp:
          type: string
          format: date-time
        base_path:
          type: string
        version:
          type: string
        pyflame_output:
          type: string
    AddedEntityResponse:
      type: object
      properties:
        id:
          type: integer
          format: int32
    AllApplicationVersions:
      type: object
      properties:
        versions:
          type: array
          items:
            type: string
