openapi: 3.0.0
info:
  version: 0.0.1
  title: Metric Handling Backend
servers:
  - url: http://localhost:8080/api
paths:
  /metrics/requests/profile/pyflame:
    post:
      summary: Add a new profile using the pyflame format
      operationId: add_pyflame_profile
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PyflameProfile'
      responses:
        '400':
          description: Error processing
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddedEntityResponse'
  /metrics/application/version:
    get:
      summary: Get all versions of an application
      operationId: get_application_versions
      parameters:
        - name: application_name
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AllApplicationVersions'
  /metrics/feedback/for_file:
    get:
      summary: Get feedback information for particular file
      operationId: get_feedback_for_file
      parameters:
        - name: application_name
          in: query
          required: true
          schema:
            type: string
        - name: version
          in: query
          required: true
          schema:
            type: string
        - name: filename
          in: query
          required: true
          schema:
            type: string
        - name: history_since_type
          in: query
          required: false
          schema:
            type: string
            enum: [date_time, beginning_of_version]
        - name: history_since_date_time
          in: query
          required: false
          schema:
            type: string
            format: date-time
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileFeedback'
        '400':
          description: Bad request
components:
  schemas:
    FeedbackFilterOptions:
      type: object
      properties:
        history_since_type:
          type: string
          enum: [date_time, beginning_of_version]
        history_since_date_time:
          type: string
          format: date-time
    FileFeedback:
      type: object
      properties:
        global_average_for_file:
          type: number
          format: double
        lines:
          type: object
          additionalProperties:
            type: object
            properties:
              general:
                $ref: '#/components/schemas/LineGeneral'
              performance:
                $ref: '#/components/schemas/LinePerformance'
              exceptions:
                $ref: '#/components/schemas/LineExceptions'
              logging:
                $ref: '#/components/schemas/LineLogging'
    LineGeneral:
      type: object
      properties:
        execution_count:
          type: integer
          format: int32
    LineExceptions:
      type: array
      items:
        $ref: '#/components/schemas/LineException'
    LinePerformance:
      type: object
      properties:
        status:
          type: string
          enum:
            - not_profiled
            - profiled
        global_average:
          type: number
          format: double
        request_profile_history:
          type: array
          items:
            type: object
            properties:
              start_timestamp:
                type: string
                format: date-time
              sample_time:
                type: number
                format: double
    LineException:
      type: object
      properties:
        exception_type:
          type: string
        exception_message:
          type: string
        exception_time:
          type: string
          format: date-time
    LineLogging:
      type: array
      items:
        $ref: '#/components/schemas/LogRecord'
    LogRecord:
      type: object
      properties:
        logger:
          type: string
        level:
          type: string
        message:
          type: string
    PyflameProfile:
      type: object
      properties:
        application_name:
          type: string
        version:
          type: string
        start_timestamp:
          type: string
          format: date-time
        end_timestamp:
          type: string
          format: date-time
        base_path:
          type: string
        instrument_directories:
          type: array
          items:
            type: string
        pyflame_output:
          type: string
        exception:
          $ref: '#/components/schemas/NewLineException'
        logging_lines:
          type: array
          items:
            $ref: '#/components/schemas/NewLogRecord'
    AddedEntityResponse:
      type: object
      properties:
        id:
          type: object
    AllApplicationVersions:
      type: object
      properties:
        versions:
          type: array
          items:
            type: string
    NewLineException:
      type: object
      properties:
        exception_type:
          type: string
        exception_message:
          type: string
        frames:
          type: array
          items:
            type: object
            properties:
              filename:
                type: string
              line_number:
                type: integer
                format: int32
              function_name:
                type: string
    NewLogRecord:
      type: object
      properties:
        line_number:
          type: integer
        filename:
          type: string
        log_record:
          $ref: '#/components/schemas/LogRecord'
